# Builds the .resx files from src/Rebornix/Resources/i18n/*.txt and checks that every language
# has exactly the same keys and the same {0}/{1} placeholders as English.
#   en.txt -> Strings.resx (default language)   tr.txt -> Strings.tr.resx   de.txt -> Strings.de.resx
# Format: one "Key=Value" per line, "\n" means a line break.
# Usage: powershell -ExecutionPolicy Bypass -File tools\gen-resx.ps1
$ErrorActionPreference = 'Stop'
$root = Join-Path $PSScriptRoot '..\src\Rebornix\Resources'
$i18n = Join-Path $root 'i18n'
$utf8 = New-Object Text.UTF8Encoding($false)

function Read-Lang([string]$file) {
    $map = [ordered]@{}
    $n = 0
    foreach ($line in [IO.File]::ReadAllLines($file, [Text.Encoding]::UTF8)) {
        $n++
        if ($line.Trim() -eq '' -or $line.StartsWith('#')) { continue }
        $i = $line.IndexOf('=')
        if ($i -lt 1) { throw "$(Split-Path $file -Leaf):$n has no '='" }
        $key = $line.Substring(0, $i)
        if ($map.Contains($key)) { throw "$(Split-Path $file -Leaf):$n duplicate key $key" }
        $map[$key] = $line.Substring($i + 1).Replace('\n', "`n")
    }
    return $map
}

function Placeholders([string]$s) {
    ([regex]::Matches($s, '\{(\d+)\}') | ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique) -join ','
}

function Write-Resx([System.Collections.Specialized.OrderedDictionary]$map, [string]$out) {
    $sb = New-Object Text.StringBuilder
    [void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
    [void]$sb.AppendLine('<!-- Generated by tools/gen-resx.ps1 from Resources/i18n/*.txt. Edit the .txt files, not this file. -->')
    [void]$sb.AppendLine('<root>')
    [void]$sb.AppendLine('  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>')
    [void]$sb.AppendLine('  <resheader name="version"><value>2.0</value></resheader>')
    [void]$sb.AppendLine('  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
    [void]$sb.AppendLine('  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
    foreach ($k in $map.Keys) {
        [void]$sb.AppendLine("  <data name=`"$k`" xml:space=`"preserve`"><value>$([Security.SecurityElement]::Escape($map[$k]))</value></data>")
    }
    [void]$sb.AppendLine('</root>')
    [IO.File]::WriteAllText($out, $sb.ToString(), $utf8)
}

$en = Read-Lang (Join-Path $i18n 'en.txt')
$errors = @()
$langs = @{}
foreach ($f in Get-ChildItem $i18n -Filter *.txt | Where-Object { $_.BaseName -ne 'en' }) {
    $map = Read-Lang $f.FullName
    $langs[$f.BaseName] = $map
    foreach ($k in $en.Keys) {
        if (-not $map.Contains($k)) { $errors += "$($f.Name): missing $k"; continue }
        if ((Placeholders $en[$k]) -ne (Placeholders $map[$k])) { $errors += "$($f.Name): placeholders differ in $k" }
    }
    foreach ($k in $map.Keys) { if (-not $en.Contains($k)) { $errors += "$($f.Name): extra key $k (not in en.txt)" } }
}
if ($errors.Count -gt 0) { $errors | ForEach-Object { Write-Host $_ -ForegroundColor Red }; exit 1 }

Write-Resx $en (Join-Path $root 'Strings.resx')
foreach ($l in $langs.Keys) { Write-Resx $langs[$l] (Join-Path $root "Strings.$l.resx") }
"OK: $($en.Count) keys, languages: en, $(($langs.Keys | Sort-Object) -join ', ')"
